services:
  - type: web
    name: sistema-financeiro-iab
    env: node
    plan: free
    buildCommand: npm run build:render
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DEFAULT_ROOT_USERNAME
        value: admin
      - key: DEFAULT_ROOT_PASSWORD
        value: Admin123!
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 